import { SeedWord } from '../types/word';

export const INITIAL_WORDS: SeedWord[] = [
  // --- DIFFICULTY 1 (sort_order 1-40) ---
  {
    en_word: 'time',
    tr_word: 'zaman',
    en_sentence: "I don't have enough time to finish this.",
    tr_sentence: 'Bunu bitirmek için yeterli zamanım yok.',
    difficulty: 1,
    sort_order: 1,
  },
  {
    en_word: 'year',
    tr_word: 'yıl',
    en_sentence: 'This year has been really challenging for everyone.',
    tr_sentence: 'Bu yıl herkes için gerçekten zorlu geçti.',
    difficulty: 1,
    sort_order: 2,
  },
  {
    en_word: 'people',
    tr_word: 'insanlar',
    en_sentence: 'Many people enjoy spending time outdoors on weekends.',
    tr_sentence: 'Pek çok insan hafta sonları dışarıda vakit geçirmeyi sever.',
    difficulty: 1,
    sort_order: 3,
  },
  {
    en_word: 'way',
    tr_word: 'yol',
    en_sentence: 'Is there a better way to solve this problem?',
    tr_sentence: 'Bu sorunu çözmenin daha iyi bir yolu var mı?',
    difficulty: 1,
    sort_order: 4,
  },
  {
    en_word: 'day',
    tr_word: 'gün',
    en_sentence: 'We had a wonderful day at the beach yesterday.',
    tr_sentence: 'Dün sahilde harika bir gün geçirdik.',
    difficulty: 1,
    sort_order: 5,
  },
  {
    en_word: 'man',
    tr_word: 'adam',
    en_sentence: 'The man at the door is asking for you.',
    tr_sentence: 'Kapıdaki adam seni soruyor.',
    difficulty: 1,
    sort_order: 6,
  },
  {
    en_word: 'woman',
    tr_word: 'kadın',
    en_sentence: 'The woman next to me was reading a thick novel.',
    tr_sentence: 'Yanımdaki kadın kalın bir roman okuyordu.',
    difficulty: 1,
    sort_order: 7,
  },
  {
    en_word: 'child',
    tr_word: 'çocuk',
    en_sentence: 'Every child deserves a safe and happy home.',
    tr_sentence: 'Her çocuk güvenli ve mutlu bir eve layıktır.',
    difficulty: 1,
    sort_order: 8,
  },
  {
    en_word: 'world',
    tr_word: 'dünya',
    en_sentence: 'Travelling helps you understand the world a little better.',
    tr_sentence: 'Seyahat etmek dünyayı biraz daha iyi anlamanı sağlar.',
    difficulty: 1,
    sort_order: 9,
  },
  {
    en_word: 'life',
    tr_word: 'hayat',
    en_sentence: 'Life is too short to waste on things that do not matter.',
    tr_sentence: 'Hayat önemli olmayan şeylere harcalamak için çok kısa.',
    difficulty: 1,
    sort_order: 10,
  },
  {
    en_word: 'hand',
    tr_word: 'el',
    en_sentence: 'She reached out her hand to help him stand up.',
    tr_sentence: 'Kalkmasına yardım etmek için elini uzattı.',
    difficulty: 1,
    sort_order: 11,
  },
  {
    en_word: 'part',
    tr_word: 'parça',
    en_sentence: 'This is the most important part of the whole project.',
    tr_sentence: 'Bu, tüm projenin en önemli parçası.',
    difficulty: 1,
    sort_order: 12,
  },
  {
    en_word: 'place',
    tr_word: 'yer',
    en_sentence: "This café is my favourite place to work in the morning.",
    tr_sentence: 'Bu kafe sabahları çalışmak için en sevdiğim yer.',
    difficulty: 1,
    sort_order: 13,
  },
  {
    en_word: 'case',
    tr_word: 'durum',
    en_sentence: 'In that case, we should probably leave a bit earlier.',
    tr_sentence: 'O durumda muhtemelen biraz daha erken ayrılmalıyız.',
    difficulty: 1,
    sort_order: 14,
  },
  {
    en_word: 'week',
    tr_word: 'hafta',
    en_sentence: 'I have been really busy every single day this week.',
    tr_sentence: 'Bu hafta her gün gerçekten çok yoğundum.',
    difficulty: 1,
    sort_order: 15,
  },
  {
    en_word: 'company',
    tr_word: 'şirket',
    en_sentence: 'The company announced new products at the conference today.',
    tr_sentence: 'Şirket bugün konferansta yeni ürünlerini duyurdu.',
    difficulty: 1,
    sort_order: 16,
  },
  {
    en_word: 'system',
    tr_word: 'sistem',
    en_sentence: 'We need to upgrade the system before the end of the month.',
    tr_sentence: 'Ay sonundan önce sistemi güncellememiz gerekiyor.',
    difficulty: 1,
    sort_order: 17,
  },
  {
    en_word: 'program',
    tr_word: 'program',
    en_sentence: 'The training program lasts for three full months.',
    tr_sentence: 'Eğitim programı tam üç ay sürüyor.',
    difficulty: 1,
    sort_order: 18,
  },
  {
    en_word: 'question',
    tr_word: 'soru',
    en_sentence: 'That is a very interesting question, let me think about it.',
    tr_sentence: 'Bu çok ilginç bir soru, bir düşüneyim.',
    difficulty: 1,
    sort_order: 19,
  },
  {
    en_word: 'work',
    tr_word: 'iş',
    en_sentence: 'Hard work and patience will always pay off eventually.',
    tr_sentence: 'Sıkı çalışma ve sabır sonunda her zaman karşılığını verir.',
    difficulty: 1,
    sort_order: 20,
  },
  {
    en_word: 'government',
    tr_word: 'hükümet',
    en_sentence: 'The government announced new regulations for small businesses.',
    tr_sentence: 'Hükümet küçük işletmeler için yeni düzenlemeler açıkladı.',
    difficulty: 1,
    sort_order: 21,
  },
  {
    en_word: 'number',
    tr_word: 'sayı',
    en_sentence: 'The number of visitors to the museum doubled last summer.',
    tr_sentence: 'Geçen yaz müzeyi ziyaret eden sayısı iki katına çıktı.',
    difficulty: 1,
    sort_order: 22,
  },
  {
    en_word: 'night',
    tr_word: 'gece',
    en_sentence: 'I could not sleep at all last night because of the noise.',
    tr_sentence: 'Dün gece gürültü yüzünden hiç uyuyamadım.',
    difficulty: 1,
    sort_order: 23,
  },
  {
    en_word: 'point',
    tr_word: 'nokta',
    en_sentence: 'You make a very valid point, I completely agree with you.',
    tr_sentence: 'Çok geçerli bir noktaya değiniyorsun, tamamen katılıyorum.',
    difficulty: 1,
    sort_order: 24,
  },
  {
    en_word: 'city',
    tr_word: 'şehir',
    en_sentence: 'Istanbul is the largest city in Turkey by population.',
    tr_sentence: "İstanbul, nüfus açısından Türkiye'nin en büyük şehri.",
    difficulty: 1,
    sort_order: 25,
  },
  {
    en_word: 'home',
    tr_word: 'ev',
    en_sentence: 'There is nothing like coming home after a long trip.',
    tr_sentence: 'Uzun bir yolculuktan sonra eve dönmek gibi bir şey yok.',
    difficulty: 1,
    sort_order: 26,
  },
  {
    en_word: 'water',
    tr_word: 'su',
    en_sentence: 'Remember to drink enough water throughout the day.',
    tr_sentence: 'Gün boyunca yeterince su içmeyi unutma.',
    difficulty: 1,
    sort_order: 27,
  },
  {
    en_word: 'room',
    tr_word: 'oda',
    en_sentence: 'The room was filled with the smell of fresh coffee.',
    tr_sentence: 'Oda taze kahve kokusuyla dolmuştu.',
    difficulty: 1,
    sort_order: 28,
  },
  {
    en_word: 'mother',
    tr_word: 'anne',
    en_sentence: 'My mother always knows exactly what to say in hard times.',
    tr_sentence: 'Annem zor zamanlarda ne söyleyeceğini her zaman bilir.',
    difficulty: 1,
    sort_order: 29,
  },
  {
    en_word: 'area',
    tr_word: 'alan',
    en_sentence: 'The park area was cleaned up by local volunteers yesterday.',
    tr_sentence: 'Park alanı dün yerel gönüllüler tarafından temizlendi.',
    difficulty: 1,
    sort_order: 30,
  },
  {
    en_word: 'money',
    tr_word: 'para',
    en_sentence: 'Saving money every month is a habit worth building early.',
    tr_sentence: 'Her ay para biriktirmek erken edinmeye değer bir alışkanlık.',
    difficulty: 1,
    sort_order: 31,
  },
  {
    en_word: 'story',
    tr_word: 'hikaye',
    en_sentence: 'She told us the most amazing story about her childhood.',
    tr_sentence: 'Bize çocukluğuyla ilgili inanılmaz bir hikaye anlattı.',
    difficulty: 1,
    sort_order: 32,
  },
  {
    en_word: 'fact',
    tr_word: 'gerçek',
    en_sentence: 'The fact that he lied makes everything much worse now.',
    tr_sentence: 'Yalan söylemiş olması her şeyi şimdi çok daha kötü yapıyor.',
    difficulty: 1,
    sort_order: 33,
  },
  {
    en_word: 'month',
    tr_word: 'ay',
    en_sentence: 'We plan to move into our new apartment next month.',
    tr_sentence: 'Gelecek ay yeni dairemize taşınmayı planlıyoruz.',
    difficulty: 1,
    sort_order: 34,
  },
  {
    en_word: 'word',
    tr_word: 'kelime',
    en_sentence: "I can't find the right word to describe how I feel.",
    tr_sentence: 'Nasıl hissettiğimi anlatacak doğru kelimeyi bulamıyorum.',
    difficulty: 1,
    sort_order: 35,
  },
  {
    en_word: 'book',
    tr_word: 'kitap',
    en_sentence: 'Have you read that book everyone has been talking about?',
    tr_sentence: 'Herkesin konuştuğu o kitabı okudun mu?',
    difficulty: 1,
    sort_order: 36,
  },
  {
    en_word: 'eye',
    tr_word: 'göz',
    en_sentence: 'Keep an eye on the bag while I go to the bathroom.',
    tr_sentence: 'Ben tuvalete giderken çantaya bir göz at.',
    difficulty: 1,
    sort_order: 37,
  },
  {
    en_word: 'job',
    tr_word: 'iş',
    en_sentence: 'She started a new job at a tech company last week.',
    tr_sentence: 'Geçen hafta bir teknoloji şirketinde yeni bir işe başladı.',
    difficulty: 1,
    sort_order: 38,
  },
  {
    en_word: 'promise',
    tr_word: 'söz',
    en_sentence: 'He always keeps his promise no matter what happens.',
    tr_sentence: 'Ne olursa olsun her zaman sözünü tutar.',
    difficulty: 1,
    sort_order: 39,
  },
  {
    en_word: 'hour',
    tr_word: 'saat',
    en_sentence: 'The meeting lasted for over an hour longer than expected.',
    tr_sentence: 'Toplantı beklenenden bir saatten fazla uzun sürdü.',
    difficulty: 1,
    sort_order: 40,
  },

  // --- DIFFICULTY 2 (sort_order 41-75) ---
  {
    en_word: 'body',
    tr_word: 'vücut',
    en_sentence: 'Regular exercise keeps both body and mind in good shape.',
    tr_sentence: 'Düzenli egzersiz hem vücudu hem de zihni formda tutar.',
    difficulty: 2,
    sort_order: 41,
  },
  {
    en_word: 'history',
    tr_word: 'tarih',
    en_sentence: 'Learning history helps us avoid repeating the same mistakes.',
    tr_sentence: 'Tarih öğrenmek aynı hataları tekrarlamamıza yardımcı olur.',
    difficulty: 2,
    sort_order: 42,
  },
  {
    en_word: 'order',
    tr_word: 'düzen',
    en_sentence: 'We need to put things in order before the guests arrive.',
    tr_sentence: 'Misafirler gelmeden önce her şeyi düzene koymamız lazım.',
    difficulty: 2,
    sort_order: 43,
  },
  {
    en_word: 'problem',
    tr_word: 'sorun',
    en_sentence: 'Every problem has a solution if you look hard enough for it.',
    tr_sentence: 'Yeterince ararsan her sorunun bir çözümü vardır.',
    difficulty: 2,
    sort_order: 44,
  },
  {
    en_word: 'country',
    tr_word: 'ülke',
    en_sentence: 'The country has seen many economic changes over the past decade.',
    tr_sentence: 'Ülke son on yılda pek çok ekonomik değişime sahne oldu.',
    difficulty: 2,
    sort_order: 45,
  },
  {
    en_word: 'school',
    tr_word: 'okul',
    en_sentence: 'She walked to school every morning rain or shine.',
    tr_sentence: 'Yağmurlu ya da güneşli her sabah okula yürüyerek giderdi.',
    difficulty: 2,
    sort_order: 46,
  },
  {
    en_word: 'family',
    tr_word: 'aile',
    en_sentence: 'Nothing matters more to me than the health of my family.',
    tr_sentence: 'Ailemin sağlığından daha önemli bir şey yok benim için.',
    difficulty: 2,
    sort_order: 47,
  },
  {
    en_word: 'learn',
    tr_word: 'öğrenmek',
    en_sentence: 'She wants to learn a new language this year.',
    tr_sentence: 'Bu yıl yeni bir dil öğrenmek istiyor.',
    difficulty: 2,
    sort_order: 48,
  },
  {
    en_word: 'state',
    tr_word: 'hal',
    en_sentence: 'The state of the economy worries many people these days.',
    tr_sentence: 'Ekonominin hali bu günlerde pek çok kişiyi endişelendiriyor.',
    difficulty: 2,
    sort_order: 49,
  },
  {
    en_word: 'leave',
    tr_word: 'ayrılmak',
    en_sentence: 'We have to leave the house before eight in the morning.',
    tr_sentence: 'Sabah sekizden önce evden ayrılmamız gerekiyor.',
    difficulty: 2,
    sort_order: 50,
  },
  {
    en_word: 'start',
    tr_word: 'başlamak',
    en_sentence: "Let's start the meeting without further delay.",
    tr_sentence: 'Toplantıya daha fazla gecikmeden başlayalım.',
    difficulty: 2,
    sort_order: 51,
  },
  {
    en_word: 'keep',
    tr_word: 'saklamak',
    en_sentence: 'You should keep your passport in a safe place.',
    tr_sentence: 'Pasaportunuzu güvenli bir yerde saklamalısınız.',
    difficulty: 2,
    sort_order: 52,
  },
  {
    en_word: 'move',
    tr_word: 'taşınmak',
    en_sentence: 'They decided to move to a bigger apartment downtown.',
    tr_sentence: 'Şehir merkezinde daha büyük bir daireye taşınmaya karar verdiler.',
    difficulty: 2,
    sort_order: 53,
  },
  {
    en_word: 'light',
    tr_word: 'ışık',
    en_sentence: 'The light in the room was too bright for sleeping.',
    tr_sentence: 'Odadaki ışık uyumak için fazla parlaktı.',
    difficulty: 2,
    sort_order: 54,
  },
  {
    en_word: 'voice',
    tr_word: 'ses',
    en_sentence: 'Her voice sounded very calm during the speech.',
    tr_sentence: 'Konuşma sırasında sesi çok sakin çıkıyordu.',
    difficulty: 2,
    sort_order: 55,
  },
  {
    en_word: 'town',
    tr_word: 'kasaba',
    en_sentence: 'She grew up in a small town near the coast.',
    tr_sentence: 'Kıyıya yakın küçük bir kasabada büyüdü.',
    difficulty: 2,
    sort_order: 56,
  },
  {
    en_word: 'friend',
    tr_word: 'arkadaş',
    en_sentence: 'My best friend called me very late last night.',
    tr_sentence: 'En iyi arkadaşım dün gece geç saatte beni aradı.',
    difficulty: 2,
    sort_order: 57,
  },
  {
    en_word: 'read',
    tr_word: 'okumak',
    en_sentence: 'I like to read a chapter before going to bed.',
    tr_sentence: 'Yatmadan önce bir bölüm okumayı severim.',
    difficulty: 2,
    sort_order: 58,
  },
  {
    en_word: 'carry',
    tr_word: 'taşımak',
    en_sentence: 'Can you carry these bags up to the third floor?',
    tr_sentence: 'Bu çantaları üçüncü kata taşıyabilir misin?',
    difficulty: 2,
    sort_order: 59,
  },
  {
    en_word: 'run',
    tr_word: 'koşmak',
    en_sentence: 'He decided to run five kilometres every morning.',
    tr_sentence: 'Her sabah beş kilometre koşmaya karar verdi.',
    difficulty: 2,
    sort_order: 60,
  },
  {
    en_word: 'food',
    tr_word: 'yemek',
    en_sentence: 'The food at that restaurant was absolutely delicious.',
    tr_sentence: 'O restorандaki yemek gerçekten harikaydı.',
    difficulty: 2,
    sort_order: 61,
  },
  {
    en_word: 'nature',
    tr_word: 'doğa',
    en_sentence: 'Spending time in nature always makes me feel much better.',
    tr_sentence: 'Doğada vakit geçirmek her zaman kendimi çok daha iyi hissettiriyor.',
    difficulty: 2,
    sort_order: 62,
  },
  {
    en_word: 'street',
    tr_word: 'sokak',
    en_sentence: 'There was a big parade down the main street today.',
    tr_sentence: 'Bugün ana sokakta büyük bir geçit töreni vardı.',
    difficulty: 2,
    sort_order: 63,
  },
  {
    en_word: 'table',
    tr_word: 'masa',
    en_sentence: 'She left her keys on the kitchen table this morning.',
    tr_sentence: 'Bu sabah anahtarlarını mutfak masasında unuttu.',
    difficulty: 2,
    sort_order: 64,
  },
  {
    en_word: 'air',
    tr_word: 'hava',
    en_sentence: 'The mountain air felt clean and refreshing all day.',
    tr_sentence: 'Dağ havası bütün gün temiz ve canlandırıcı geldi.',
    difficulty: 2,
    sort_order: 65,
  },
  {
    en_word: 'paper',
    tr_word: 'kağıt',
    en_sentence: 'Please write your name on the top of the paper.',
    tr_sentence: 'Lütfen adınızı kağıdın en üstüne yazın.',
    difficulty: 2,
    sort_order: 66,
  },
  {
    en_word: 'answer',
    tr_word: 'cevap',
    en_sentence: 'I did not know the answer to that difficult question.',
    tr_sentence: 'O zor sorunun cevabını bilmiyordum.',
    difficulty: 2,
    sort_order: 67,
  },
  {
    en_word: 'study',
    tr_word: 'çalışmak',
    en_sentence: 'You need to study every day to pass the exam.',
    tr_sentence: 'Sınavı geçmek için her gün çalışman gerekiyor.',
    difficulty: 2,
    sort_order: 68,
  },
  {
    en_word: 'heart',
    tr_word: 'kalp',
    en_sentence: 'Her heart was beating fast before the big presentation.',
    tr_sentence: 'Büyük sunumdan önce kalbi hızla çarpıyordu.',
    difficulty: 2,
    sort_order: 69,
  },
  {
    en_word: 'plant',
    tr_word: 'bitki',
    en_sentence: 'She watered the plant on the windowsill this morning.',
    tr_sentence: 'Bu sabah pencere kenarındaki bitkiyi suladı.',
    difficulty: 2,
    sort_order: 70,
  },
  {
    en_word: 'cover',
    tr_word: 'örtmek',
    en_sentence: 'Please cover the food before putting it in the fridge.',
    tr_sentence: 'Yiyeceği buzdolabına koymadan önce lütfen üzerini örtün.',
    difficulty: 2,
    sort_order: 71,
  },
  {
    en_word: 'power',
    tr_word: 'güç',
    en_sentence: 'Knowledge gives you the power to change your circumstances.',
    tr_sentence: 'Bilgi, koşullarını değiştirme gücü verir sana.',
    difficulty: 2,
    sort_order: 72,
  },
  {
    en_word: 'field',
    tr_word: 'alan',
    en_sentence: 'She is one of the leading experts in her field worldwide.',
    tr_sentence: 'Dünya genelinde alanındaki önde gelen uzmanlardan biri.',
    difficulty: 2,
    sort_order: 73,
  },
  {
    en_word: 'group',
    tr_word: 'grup',
    en_sentence: 'A group of students stayed after class to ask questions.',
    tr_sentence: 'Bir grup öğrenci soru sormak için dersten sonra kaldı.',
    difficulty: 2,
    sort_order: 74,
  },
  {
    en_word: 'moment',
    tr_word: 'an',
    en_sentence: 'Can you wait just one moment while I find my phone?',
    tr_sentence: 'Telefonumu ararken bir an bekleyebilir misin?',
    difficulty: 2,
    sort_order: 75,
  },

  // --- DIFFICULTY 3 (sort_order 76-100) ---
  {
    en_word: 'health',
    tr_word: 'sağlık',
    en_sentence: 'Good sleep is essential for your overall health.',
    tr_sentence: 'İyi uyku genel sağlığınız için çok önemlidir.',
    difficulty: 3,
    sort_order: 76,
  },
  {
    en_word: 'develop',
    tr_word: 'geliştirmek',
    en_sentence: 'The company wants to develop a new mobile application.',
    tr_sentence: 'Şirket yeni bir mobil uygulama geliştirmek istiyor.',
    difficulty: 3,
    sort_order: 77,
  },
  {
    en_word: 'remember',
    tr_word: 'hatırlamak',
    en_sentence: 'I always remember to call my parents on Sunday evenings.',
    tr_sentence: 'Pazar akşamları ailemi aramayı her zaman hatırlarım.',
    difficulty: 3,
    sort_order: 78,
  },
  {
    en_word: 'side',
    tr_word: 'taraf',
    en_sentence: 'Please stand on the left side of the elevator door.',
    tr_sentence: 'Lütfen asansör kapısının sol tarafında durun.',
    difficulty: 3,
    sort_order: 79,
  },
  {
    en_word: 'turn',
    tr_word: 'dönmek',
    en_sentence: 'Turn right at the traffic lights to reach the park.',
    tr_sentence: 'Parka ulaşmak için trafik ışıklarında sağa dönün.',
    difficulty: 3,
    sort_order: 80,
  },
  {
    en_word: 'experience',
    tr_word: 'deneyim',
    en_sentence: 'Working abroad was a life-changing experience for him.',
    tr_sentence: 'Yurt dışında çalışmak onun için hayat değiştiren bir deneyimdi.',
    difficulty: 3,
    sort_order: 81,
  },
  {
    en_word: 'reach',
    tr_word: 'ulaşmak',
    en_sentence: 'We need to reach the airport at least two hours early.',
    tr_sentence: 'Havalimanına en az iki saat erken ulaşmamız gerekiyor.',
    difficulty: 3,
    sort_order: 82,
  },
  {
    en_word: 'offer',
    tr_word: 'teklif',
    en_sentence: 'She received an amazing job offer from a tech company.',
    tr_sentence: 'Bir teknoloji şirketinden harika bir iş teklifi aldı.',
    difficulty: 3,
    sort_order: 83,
  },
  {
    en_word: 'build',
    tr_word: 'inşa etmek',
    en_sentence: 'They plan to build a new bridge across the river.',
    tr_sentence: 'Nehrin üzerine yeni bir köprü inşa etmeyi planlıyorlar.',
    difficulty: 3,
    sort_order: 84,
  },
  {
    en_word: 'strong',
    tr_word: 'güçlü',
    en_sentence: 'You need a strong password to protect your account.',
    tr_sentence: 'Hesabınızı korumak için güçlü bir şifre belirlemeniz gerekiyor.',
    difficulty: 3,
    sort_order: 85,
  },
  {
    en_word: 'society',
    tr_word: 'toplum',
    en_sentence: 'Education plays a key role in shaping a healthy society.',
    tr_sentence: 'Eğitim, sağlıklı bir toplum şekillendirmede kilit rol oynar.',
    difficulty: 3,
    sort_order: 86,
  },
  {
    en_word: 'young',
    tr_word: 'genç',
    en_sentence: 'The young doctor impressed everyone with her knowledge.',
    tr_sentence: 'Genç doktor bilgisiyle herkesi etkiledi.',
    difficulty: 3,
    sort_order: 87,
  },
  {
    en_word: 'pay',
    tr_word: 'ödemek',
    en_sentence: 'Did you remember to pay the electricity bill this month?',
    tr_sentence: 'Bu ay elektrik faturasını ödemeyi unuttun mu?',
    difficulty: 3,
    sort_order: 88,
  },
  {
    en_word: 'believe',
    tr_word: 'inanmak',
    en_sentence: 'I believe hard work always leads to success in the end.',
    tr_sentence: 'Sıkı çalışmanın sonunda başarıya götürdüğüne inanıyorum.',
    difficulty: 3,
    sort_order: 89,
  },
  {
    en_word: 'include',
    tr_word: 'içermek',
    en_sentence: 'The price does not include breakfast at this hotel.',
    tr_sentence: 'Bu otelde fiyat kahvaltıyı içermiyor.',
    difficulty: 3,
    sort_order: 90,
  },
  {
    en_word: 'result',
    tr_word: 'sonuç',
    en_sentence: 'The result of the experiment surprised the whole team.',
    tr_sentence: 'Deneyin sonucu tüm ekibi şaşırttı.',
    difficulty: 3,
    sort_order: 91,
  },
  {
    en_word: 'decision',
    tr_word: 'karar',
    en_sentence: 'Making a good decision under pressure is never easy.',
    tr_sentence: 'Baskı altında iyi bir karar vermek hiç kolay değil.',
    difficulty: 3,
    sort_order: 92,
  },
  {
    en_word: 'sense',
    tr_word: 'his',
    en_sentence: 'I had a strange sense that something was about to happen.',
    tr_sentence: 'Bir şeylerin olmak üzere olduğuna dair garip bir his vardı içimde.',
    difficulty: 3,
    sort_order: 93,
  },
  {
    en_word: 'event',
    tr_word: 'etkinlik',
    en_sentence: 'The city organized a big cultural event last weekend.',
    tr_sentence: 'Şehir geçen hafta sonu büyük bir kültürel etkinlik düzenledi.',
    difficulty: 3,
    sort_order: 94,
  },
  {
    en_word: 'early',
    tr_word: 'erken',
    en_sentence: 'She always arrives early to prepare for the class.',
    tr_sentence: 'Derse hazırlanmak için her zaman erken gelir.',
    difficulty: 3,
    sort_order: 95,
  },
  {
    en_word: 'support',
    tr_word: 'destek',
    en_sentence: 'Your support means a great deal to me right now.',
    tr_sentence: 'Şu an desteğin benim için çok büyük bir anlam taşıyor.',
    difficulty: 3,
    sort_order: 96,
  },
  {
    en_word: 'language',
    tr_word: 'dil',
    en_sentence: 'Learning a second language opens many doors in life.',
    tr_sentence: 'İkinci bir dil öğrenmek hayatta pek çok kapı açar.',
    difficulty: 3,
    sort_order: 97,
  },
  {
    en_word: 'happen',
    tr_word: 'olmak',
    en_sentence: 'What will happen if we miss the last train tonight?',
    tr_sentence: 'Bu gece son treni kaçırırsak ne olacak?',
    difficulty: 3,
    sort_order: 98,
  },
  {
    en_word: 'understand',
    tr_word: 'anlamak',
    en_sentence: 'It took me a while to understand what she really meant.',
    tr_sentence: 'Ne demek istediğini anlamam biraz zaman aldı.',
    difficulty: 3,
    sort_order: 99,
  },
  {
    en_word: 'change',
    tr_word: 'değişmek',
    en_sentence: 'Things will change once you move to a new city.',
    tr_sentence: 'Yeni bir şehre taşındığında her şey değişecek.',
    difficulty: 3,
    sort_order: 100,
  },
];
